### ISSUE TITLE
Show bad data

### ISSUE THREAD

**Issue by sagitt** [kodi1/tvh_rec#4]
![Immagine](https://user-images.githubusercontent.com/169086/92576299-aae81800-f289-11ea-9e01-1fdc413fd3a7.png)

**Comment by kodi1** [comment]
how did you expect problem tobe resolved without any additional info?

**Comment by sagitt** [comment]
> how did you expect problem tobe resolved without any additional info?

What info you need? Please tell me. I'll give you
